# Build image
image: macos-sonoma

install:
# Install rustup
- curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile=minimal
# Install cargo-nextest
- curl -LsSf https://get.nexte.st/latest/mac | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
- export PATH=$HOME/.cargo/bin:$PATH
- cargo fetch --locked
test_script:
# First, build all the tests
- cargo nextest run --no-run --verbose --locked --offline --all-features
# Then, add entitlement to all test binaries
- find target/debug/deps -perm +111 -type f | grep -v '\.dylib$' | xargs -I '{}' codesign -s - --entitlements endpoint-sec/Entitlement.plist --force {}
# Now we can run them
- sudo cargo nextest run --verbose --locked --offline --all-features

build: off
